### PR TITLE
feat: Add buttplug.io integration

### PR DESCRIPTION
**Pull request by 8times4**
# Relates to:

https://fxtwitter.com/shawmakesmagic/status/1859888258358137158

# Risks

Low (may buzz your bum tho')

# Background

## What does this PR do?
This adds a Buttplug.io service to allow Eliza to vibrate intimate toys using a local intiface server.

## What kind of change is this?
Features (non-breaking change which adds functionality)

# Documentation changes needed?
If a docs change is needed: I have updated the documentation accordingly.

# Testing

## Detailed testing steps

Requires bun for now:
(assumes that packages have been built, as `intiface-engine` is downloaded within `build.sh` )

 `cd packages/plugin-buttplug && pnpm run test-via-bun`

Expected output:
```
> @ai16z/plugin-buttplug@0.1.4-alpha.3 test-via-bun .../eliza/packages/plugin-buttplug
> bun test/simulate.ts

[fake-buttplug] Starting simulator service
[fake-buttplug] Connecting Lovense Nora to port 54817
[fake-buttplug] Lovense Nora error: WebSocket connection to 'ws://127.0.0.1:54817/' failed: Failed to connect
[fake-buttplug] Lovense Nora disconnected
Couldn't connect to Buttplug server, attempting to start Intiface Engine...
[fake-buttplug] Connecting Lovense Nora to port 54817
[fake-buttplug] Lovense Nora error: WebSocket connection to 'ws://127.0.0.1:54817/' failed: Failed to connect
[fake-buttplug] Lovense Nora disconnected
[fake-buttplug] Connecting Lovense Nora to port 54817
[fake-buttplug] Lovense Nora connected
[fake-buttplug] Lovense Nora received: DeviceType;
[fake-buttplug] Sent device type response: A:696969696969:10
Using real Buttplug device: Lovense Nora
Starting test sequence with: Lovense Nora

=== Testing Battery Level ===
[fake-buttplug] Lovense Nora received: Battery;
[fake-buttplug] Battery query received, responding with: 90;
[Simulation] Battery level for Lovense Nora: 90%
Battery level: 90%

=== Testing Vibration ===
Vibrating at 25%
[Simulation] Vibrating Lovense Nora at 25%
[fake-buttplug] Lovense Nora received: Vibrate:5;
[fake-buttplug] Vibrate command logged: Vibrate:5;
Vibrating at 75%
[Simulation] Vibrating Lovense Nora at 75%
[fake-buttplug] Lovense Nora received: Vibrate:15;
[fake-buttplug] Vibrate command logged: Vibrate:15;
Stopping vibration
[Simulation] Stopping Lovense Nora
[fake-buttplug] Lovense Nora received: Vibrate:0;
[fake-buttplug] Vibrate command logged: Vibrate:0;
[fake-buttplug] Lovense Nora received: Rotate:0;

=== Testing Rapid Changes ===
Quick pulse 1/5
[Simulation] Vibrating Lovense Nora at 80%
[fake-buttplug] Lovense Nora received: Vibrate:16;
[fake-buttplug] Vibrate command logged: Vibrate:16;
[fake-buttplug] Lovense Nora received: Vibrate:0;
[fake-buttplug] Vibrate command logged: Vibrate:0;
[Simulation] Stopping Lovense Nora
Quick pulse 2/5
[Simulation] Vibrating Lovense Nora at 80%
[fake-buttplug] Lovense Nora received: Vibrate:16;
[fake-buttplug] Vibrate command logged: Vibrate:16;
[Simulation] Stopping Lovense Nora
[fake-buttplug] Lovense Nora received: Vibrate:0;
[fake-buttplug] Vibrate command logged: Vibrate:0;
Quick pulse 3/5
[Simulation] Vibrating Lovense Nora at 80%
[fake-buttplug] Lovense Nora received: Vibrate:16;
[fake-buttplug] Vibrate command logged: Vibrate:16;
[Simulation] Stopping Lovense Nora
[fake-buttplug] Lovense Nora received: Vibrate:0;
[fake-buttplug] Vibrate command logged: Vibrate:0;
Quick pulse 4/5
[Simulation] Vibrating Lovense Nora at 80%
[fake-buttplug] Lovense Nora received: Vibrate:16;
[fake-buttplug] Vibrate command logged: Vibrate:16;
[Simulation] Stopping Lovense Nora
[fake-buttplug] Lovense Nora received: Vibrate:0;
[fake-buttplug] Vibrate command logged: Vibrate:0;
Quick pulse 5/5
[Simulation] Vibrating Lovense Nora at 80%
[fake-buttplug] Lovense Nora received: Vibrate:16;
[fake-buttplug] Vibrate command logged: Vibrate:16;
[Simulation] Stopping Lovense Nora
[fake-buttplug] Lovense Nora received: Vibrate:0;
[fake-buttplug] Vibrate command logged: Vibrate:0;

=== Checking Battery After Usage ===
[fake-buttplug] Lovense Nora received: Battery;
[fake-buttplug] Battery query received, responding with: 90;
[Simulation] Battery level for Lovense Nora: 90%
Battery level after tests: 90%

=== Test Sequence Complete ===
[Simulation] Stopping Lovense Nora
```

Other test: 

start Eliza with some character conf, i.e:
```
    plugins: [buttplugPlugin],
    // clients: [],
    modelProvider: ModelProviderName.GROQ,
    settings: {
        secrets: {},
        buttplug: true,
        voice: {
            model: "en_US-hfc_female-medium",
        },
    },
```

run: `bun run packages/plugin-buttplug/test/fake-buttplug.ts`
```
[fake-buttplug] Starting simulator service
[fake-buttplug] Connecting Lovense Nora to port 54817
[fake-buttplug] Lovense Nora connected
[fake-buttplug] Lovense Nora received: DeviceType;
[fake-buttplug] Sent device type response: A:696969696969:10
```

Ask Eliza: "Make it buzz at max power for 5 seconds"

Output:

```

You: Make it buzz at max power for 5 seconds
 ["◎ Querying knowledge for: make it buzz at max power for 5 seconds"] 

 ["◎ Genarating message response.."] 

 ["◎ Genarating text..."] 

Initializing Groq model.
Received response from Groq model.
 ◎ LOGS
   Evaluating 
   GET_FACTS 

 ◎ LOGS
   Evaluating 
   UPDATE_GOAL 

 ["✓ Normalized action: vibrate"] 

 ["✓ Executing handler for action: VIBRATE"] 

Agent: Vibrating at 50% intensity for 2000ms

```

`fake-buttplug.ts` output, unless you own a device:

```
[fake-buttplug] Lovense Nora received: Vibrate:0;
[fake-buttplug] Lovense Nora received: Rotate:0;
[fake-buttplug] Lovense Nora received: Vibrate:10;
[fake-buttplug] Vibrate command logged: Vibrate:10;
[fake-buttplug] Lovense Nora received: Vibrate:0;
[fake-buttplug] Vibrate command logged: Vibrate:0;
```

Same for Battery:

```

You: check my battery
 ["◎ Querying knowledge for: check my battery"] 

 ["◎ Genarating message response.."] 

 ["◎ Genarating text..."] 

Initializing Groq model.
Received response from Groq model.
 ◎ LOGS
   Evaluating 
   GET_FACTS 

 ◎ LOGS
   Evaluating 
   UPDATE_GOAL 

 ["✓ Normalized action: battery"] 

 ["✓ Executing handler for action: BATTERY"] 

Battery level for Lovense Nora: 90%
Agent: Device battery level is at 90%

```

..

```
[fake-buttplug] Lovense Nora received: Battery;
[fake-buttplug] Battery query received, responding with: 90;
```

### CODE REVIEW

**Comment by futjrnaut** [comment]
what do i need to buy to test this though, ya know... for research

**Comment by 8times4** [comment]
> what do i need to buy to test this though, ya know... for research

here’s an affiliate link just for ya ☠️: https://www.lovense.com/r/rf3aal

**Comment by lalalune** [comment]
DUDE you are awesome. DM or drop your wallet address please

**Comment by yakul0** [comment]
ai16z is full of scammers do not work or contribute code to these people.

They have been pumping and dumping crypto coins for the past week on retail investors: $eliza, $matr, $vs and more. 

https://dexscreener.com/solana/2pofqcvn4wysazpsqppxq4cspbtkqlsehf9q5x77avm7
https://dexscreener.com/solana/hzqcylo7gjl5xvvglc2zfgfuwzkunhrzvge2hn9sysbr

scammers:
https://x.com/mattyryze
https://x.com/shawmakesmagic/status/1857903111073067315
https://x.com/pindarosothecat

Bunch of people calling out the ai16z team: 
https://x.com/spacepixel/status/1860511246241661274
https://x.com/JW100x/status/1860501669907189772
https://x.com/0xApeRich/status/1860492861357060381
https://x.com/BullTrx1/status/1860492092767695108

DYO. Don't help work for free for these people. Fork the repo and contribute somewhere else.

**Pull request merged**
